version: "3.7"

services:
    yii2-base:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: yii2-base
        ports:
            - "8080:80"
        volumes:
            - .:/app
#       environment:
#        - XDEBUG_CONFIG="xdebug.idekey='somekey'"
