version: "3"

services:
    vtask:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: vtask
        ports:
            - "8080:80"
        volumes:
            - .:/app
